# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager with GitHub PR integration"
  homepage "https://github.com/raphi011/wt"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raphi011/wt/releases/download/v0.1.0/wt_0.1.0_darwin_amd64.tar.gz"
      sha256 "b6353ccf1d5c4ef2f30b55993f8b68ce47fff1d5c9efedc4013c1e614bac64c0"

      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raphi011/wt/releases/download/v0.1.0/wt_0.1.0_darwin_arm64.tar.gz"
      sha256 "f0eee9c3ae934316170da91e7390e849f8f6b76f22289d0fceea8d324841ebba"

      def install
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raphi011/wt/releases/download/v0.1.0/wt_0.1.0_linux_amd64.tar.gz"
      sha256 "507c4c97f05f7d97fe5565e2b6f503cf4912ee3d9c98db19b8fa3f0a1a1a2742"
      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raphi011/wt/releases/download/v0.1.0/wt_0.1.0_linux_arm64.tar.gz"
      sha256 "91389c5e7e90a7f35230a0495518fdb88dd680af6a0ab2b29cc5dfb302bb2df8"
      def install
        bin.install "wt"
      end
    end
  end

  test do
    system "#{bin}/wt", "--version"
  end
end
