# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager with GitHub PR integration"
  homepage "https://github.com/raphi011/wt"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  on_macos do
    on_intel do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
      sha256 "0232d19a54fa4bd12118f303f2b6baac73019f83b493b94075a970d0ca2337a8"
    end
    on_arm do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
      sha256 "648d3b07e5369236abffcc6da5611f3eda22328de59896737e9365c90927b346"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
      sha256 "51fd46241c8a500e411c3758cd73f51d9da5cad0b37163d26e71fb0acdc8009e"
    end
    on_arm do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
      sha256 "05646fca812bbc9326b33d3214bcaa77144d0a046c6fcbe95f2ff62b77c634cc"
    end
  end

  # No zap stanza required
end
