# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager with GitHub PR integration"
  homepage "https://github.com/raphi011/wt"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  on_macos do
    on_intel do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
      sha256 "34639e05f5c24d9743680f2b74fa60b18b2345e55f6dc48d525c353fee626885"
    end
    on_arm do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
      sha256 "f035bbfe65c145c61f5a753c529655a43133b789d467fbf64116a442ea33202f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
      sha256 "843ba115ed3d0f61e69d39cdc60a546a98b6a57e1985f362973032abeea9e098"
    end
    on_arm do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
      sha256 "65ae63cc638fdba21bec71500aad413b81ce3280f05f572f0e13238dd0f37000"
    end
  end

  # No zap stanza required
end
