# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager with GitHub PR integration"
  homepage "https://github.com/raphi011/wt"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  on_macos do
    on_intel do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
      sha256 "cd0b60530030ecece8c91c1bbff6ec0fa2bccb5807ee33279bf1075c6df5a179"
    end
    on_arm do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
      sha256 "490eeaa2aaef70fc9f9eddb8c9eb6222e75e7fd0ad71397a758b780f05c4164f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
      sha256 "4c5bfe0741b56cfb36ddf3b0cf4a0f227fda1bbe974970f2e3aa9b986f85fe60"
    end
    on_arm do
      url "https://github.com/raphi011/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
      sha256 "f7dff1668139091f6f81a3ebf8859438444ac45c622b7f785db1c5bdc31342ff"
    end
  end

  # No zap stanza required
end
