# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager with GitHub PR integration"
  homepage "https://github.com/raphi011/wt"
  version "0.29.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raphi011/wt/releases/download/v0.29.0/wt_0.29.0_darwin_amd64.tar.gz"
      sha256 "9c878cbb7b8ea9d94725c82f51166526afb92fc3f4e87fef2646606acb3823c9"

      define_method(:install) do
        bin.install "wt"
        bash_completion.install "completions/wt.bash" => "wt"
        zsh_completion.install "completions/_wt"
        fish_completion.install "completions/wt.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raphi011/wt/releases/download/v0.29.0/wt_0.29.0_darwin_arm64.tar.gz"
      sha256 "af51525a806951eebf9f8c48ac1fc7c5967d2f6729637e0b380b3b8214453933"

      define_method(:install) do
        bin.install "wt"
        bash_completion.install "completions/wt.bash" => "wt"
        zsh_completion.install "completions/_wt"
        fish_completion.install "completions/wt.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raphi011/wt/releases/download/v0.29.0/wt_0.29.0_linux_amd64.tar.gz"
      sha256 "404406f04c66f4c3b16fcb11b947167a2d11cdf543a2cd2024702c809a0536a4"
      define_method(:install) do
        bin.install "wt"
        bash_completion.install "completions/wt.bash" => "wt"
        zsh_completion.install "completions/_wt"
        fish_completion.install "completions/wt.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raphi011/wt/releases/download/v0.29.0/wt_0.29.0_linux_arm64.tar.gz"
      sha256 "9c606a76d8e9e06b1cad337a3c75fc666a20ab779935d8bafcc76181b5b1e394"
      define_method(:install) do
        bin.install "wt"
        bash_completion.install "completions/wt.bash" => "wt"
        zsh_completion.install "completions/_wt"
        fish_completion.install "completions/wt.fish"
      end
    end
  end
end
