# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager with GitHub PR integration"
  homepage "https://github.com/raphi011/wt"
  version "0.34.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raphi011/wt/releases/download/v0.34.0/wt_0.34.0_darwin_amd64.tar.gz"
      sha256 "af7f7c0680de4a0dd2acab8eb150e57635c540bd1b44a2a1814a07d08201e674"

      define_method(:install) do
        bin.install "wt"
        bash_completion.install "completions/wt.bash" => "wt"
        zsh_completion.install "completions/_wt"
        fish_completion.install "completions/wt.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raphi011/wt/releases/download/v0.34.0/wt_0.34.0_darwin_arm64.tar.gz"
      sha256 "37d0de3c468815dff4ddef67c8fe13c438d24800b068350ff8a5c167fa9a2543"

      define_method(:install) do
        bin.install "wt"
        bash_completion.install "completions/wt.bash" => "wt"
        zsh_completion.install "completions/_wt"
        fish_completion.install "completions/wt.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raphi011/wt/releases/download/v0.34.0/wt_0.34.0_linux_amd64.tar.gz"
      sha256 "ad16c4f183555f4ebe9fc8d64381bf340427f05b07f6eac9212be79581a47dba"
      define_method(:install) do
        bin.install "wt"
        bash_completion.install "completions/wt.bash" => "wt"
        zsh_completion.install "completions/_wt"
        fish_completion.install "completions/wt.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raphi011/wt/releases/download/v0.34.0/wt_0.34.0_linux_arm64.tar.gz"
      sha256 "01b0bce463c9524fc302c59ba41cfcd3473a0d869343c4dc3c266fdf32e0afc7"
      define_method(:install) do
        bin.install "wt"
        bash_completion.install "completions/wt.bash" => "wt"
        zsh_completion.install "completions/_wt"
        fish_completion.install "completions/wt.fish"
      end
    end
  end
end
